/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 *
 * SPDX-License-Identifier: Net-SNMP
 * License-Filename: LICENSES/Net-SNMP.txt
 */
#ifndef NSTMIBOBJECTS_H
#define NSTMIBOBJECTS_H

/*
 * function declarations 
 */
void            init_nstMIBObjects(void);
Netsnmp_Node_Handler handle_nstAgentModuleObject;
Netsnmp_Node_Handler handle_nstAgentSubagentObject;
Netsnmp_Node_Handler handle_nstAgentPluginObject;

#endif                          /* NSTMIBOBJECTS_H */
